### ISSUE TITLE
Team / Members section is missing. 

### ISSUE THREAD

**Issue by blockone** [decred/dcrweb#101]
Why no members section? Would be extremely good from a marketing perspective. High dollar investors invest in teams, yet, i fail to see a single team member on the main website? How is this cryptocurrency being built, who is leading it? Can i trust them? Who is developing decred? Am I inspired by previous projects they have worked on? Who is doing their marketing? Who is writing their documentation? Who is responsible for this sweet website? Is it all just materializing from the ether? I wish there was an easy way we could give recognition to all the people that help contribute to this project, while at the same time inspiring confidence in this great crypto project. If only there was a way.

**Comment by gratefulcheddar** [comment]
My thoughts on this:

I don't know if we can mimic the way other coins highlight who is on their team, because Decred is a self-funded project that aims to incentivize decentralized development and other work, something that has never been attempted before.

Currently the site says:

> Development
>
> Decred fosters a multi-stakeholder development ecosystem that welcomes and empowers participants who want to improve on existing features or build new tools. 
> 
> Anyone can submit feature proposals, and developers are paid for work to fulfill requirements in full view of the community.  Funding for this work comes directly from the Decred blockchain.

I think we should highlight the the number of people and the geographical diversity of everyone currently involved as a contractor so that people passing by can see the results of Decred's self-funding. Maybe include a link to the ever-changing support directory [here](https://docs.decred.org/support-directory/).

**Comment by sndurkin** [comment]
> I think we should highlight the number of people and the geographical diversity (credit to lustosa) of everyone currently involved as a contractor so that people passing by can see the results of Decred's self-funding.

I agree. It would be cool to replace the support directory page with a team page that's linked from decred.org, and maybe include short bios on the main developers/designers/community managers, then have an "Other contractors" section that highlights all the other contributors and provides a link to join the team.

**Comment by linnutee** [comment]
Already in the pipeline.

**Comment by noahpierau** [comment]
https://www.decred.org/contributors/ this issue can be closed @karamble

**Comment by jolan** [comment]
Closed via #159.
