### ISSUE TITLE
Priority fixes

### ISSUE THREAD

**Issue by linnutee** [decred/dcrweb#109]
Alright so it seems some of the changes that have been implemented since adding the languages have caused a number of critical issues that need urgent fixing. 

1) Navigation button not clickable macOS 10.12 Safari 

2) All of the possible download versions are as visible buttons on mobile views below 768 px width breakpoint . So the download detection isn't working there. In the mobile views this should offer to re-direct to the downloads subpage and not suggest multiple or any options that are not relevant for the device. 

<img width="393" alt="screen shot 2017-08-19 at 14 35 53" src="https://user-images.githubusercontent.com/17774057/29486333-e058cd40-84eb-11e7-968f-796c3c773154.png">

3) Tour Sections expandable points are all open/not working in a number of devices and browsers.
<img width="305" alt="screen shot 2017-08-19 at 14 50 33" src="https://user-images.githubusercontent.com/17774057/29486422-c964369a-84ed-11e7-8e3d-a8f958c404a7.png">

4) The Statistics section isn't functioning (mac + ios safari and some windows phones) 
<img width="1387" alt="screen shot 2017-08-19 at 14 45 19" src="https://user-images.githubusercontent.com/17774057/29486423-d1432df8-84ed-11e7-9fce-9be50024b7e5.png">

A set from browserstack screenshots also: 
[browserstack - decred.org - 19082017.zip](https://github.com/decred/dcrweb/files/1236326/browserstack.-.decred.org.-.19082017.zip)

**Comment by peterzen** [comment]
Platform: safari 10.1.2 macOS 10.12.6

#1 can't reproduce, nav button is clickable & opens drawer

#2 on my screen buttons start stacking @ <580px, looks like a CSS issue

![image](https://user-images.githubusercontent.com/5878500/29490651-dc582e28-8542-11e7-9bfe-d30f2e4fd084.png)

#3 Tour section renders correctly.  (this kind of layout breakage can happen when there's a JS error and the layout doesn't get initialized - @linnutee can you please see if there's a JS exception?

#4 this may potentially be caused by an earlier JS exception (I can't reproduce it)

**Comment by oktapodia** [comment]
1. The navigation button does not work when the website is loading and I think this is the issue, we can first minify the JS/CSS files and then maybe adding a loader
