### ISSUE TITLE
Spanish and PT languages showing english on main page

### ISSUE THREAD

**Issue by exitus1** [decred/dcrweb#1156]
![image](https://github.com/decred/dcrweb/assets/46197055/bc55ce3b-1212-4b87-b44b-3c921ea40562)

**Comment by jholdstock** [comment]
There is no technical bug here - the English version of a string is displayed when the translated version is missing. This is intended behaviour because the alternatives are to display nothing in that space, or to completely remove that translation from the site.

Its quite subjective to decide when to keep/remove a language based on how much of it is available. Perhaps we need some kind of policy in place - e.g. remove a language if >20% of the strings are unavailable.

**Comment by xaur** [comment]
If a translated string is missing showing English string is a good graceful degradation to me.

If a translated string exists but becomes inaccurate over time this is more dangerous. Worst case is it may lead the reader to a wrong decision. From an English side we can avoid this by watching for "breaking changes" in the meaning of English strings, or introduce new IDs instead of changing the meaning of existing IDs.

As for removals, we could benefit from a mechanism to disable a translation without removing it from the repo. Like a simple text file with a list of enabled translations (positive lists and booleans are more robust imo). It will make it easier for translators to update and "resurrect" the translation on the site without digging through Git history.

**Comment by jholdstock** [comment]
That mechanism already exists in [config.yml](https://github.com/decred/dcrweb/blob/372670a97d33205fb6039eab09d0f6389c691ffd/src/config.yml#L24)

**Comment by xaur** [comment]
Super cool thank you!

I posted this issue in #translators to see if anyone can patch the strings.

**Comment by exitus1** [comment]
Old main page, now irrelevant.
