### ISSUE TITLE
reorder decrediton wallet download links on downloads page

### ISSUE THREAD

**Issue by behindtext** [decred/dcrweb#170]
not sure what site stats say, but we should order the links for decrediton from left to right in the order that they are most often downloaded, e.g. if Windows is #1, it should be 1st from the left, etc.

**Comment by peterzen** [comment]
The site stats don't have these data as the download links point to the Github releases.  Are there relevant numbers in Github perhaps?

**Comment by nickboariu** [comment]
Pulled data from Piwik. Can’t see the exact download numbers by wallet version because the goal is set to trigger on “Click on a Link to an external website. Pattern contains: github.com/decred”. These visits / conversion rates should provide enough insight.
![decred-webanalytics-conversions-os-family](https://user-images.githubusercontent.com/12702524/33249663-b37f00a8-d2e0-11e7-9021-9d22cde0a3cc.PNG)
