### ISSUE TITLE
[SUGGESTION] Improve Language Selector drop down menu for consistency.

### ISSUE THREAD

**Issue by gravityz3r0** [decred/dcrweb#289]
As of now, regardless of language selected the default word is LANG, which means language as we all know.

However, this may not be understood and be immediately obvious to non-english speaker, thus they may not even know that the language selection menu is there.

To make thing worse, even if you changed the language to Chinese for example, the drop down menu default text remained as LANG, which is inconsistent with the rest of the website which has been translated to Chinese.

To improve this and for consistency, why not replace the word LANG with the respective country's flag. Everybody knows that country's flag is a universal sign for language selector in a website.

I.e: LANG should be replaced with a British Flag or maybe a combination of both.

**Comment by denyszayets** [comment]
I like your idea. Thanks for your suggestion.

**Comment by linnutee** [comment]
Good catch. Would tag this as a bug, as i'm not sure how the LANG has ended up there. Seems to be an unfinished work-around.

The intended function is to display only selected languages shortcodes in the dropdown. By default this would be ENG. When a language is changed, the selected one should be shown instead of LANG. To solve this, LANG just needs to be removed. @rmykolas up for sorting this out?

<img width="642" alt="screen shot 2018-05-26 at 19 44 23" src="https://user-images.githubusercontent.com/17774057/40578485-7a61d20c-611d-11e8-8e77-3af92eefe77e.png">

Regarding flags, i'm not in favour of bringing those into decred.org, since flags don't represent languages. Languages are often spoken across national borders. I think it may be fine to use it in some contexts certainly, but needs to come with a relevant language name or iso code (and even then there's still potential issues, esp. with more languages). Also would add needless bloat to the site. 

Second point around detecting language selector – although a flag will give indication of lang selector, this is a matter of iconography as well general layout clarity. I would say the language selector is located in a fairly expected and clear position, so it's not necessarily an issue until there's actual reports of not finding the language selector. Will consider adding an icon in a future release as an enhancement.

**Comment by rmykolas** [comment]
This can be closed
