### ISSUE TITLE
[improvement] additional info on Community page

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrweb#373]
On https://www.decred.org/community/ we could show additional information to make the page more useful to newcomers. One aspect is follower count on social media, so people can see how big the Decred community is. Another idea is activity stats and descriptions for the different platforms, so people can more easily find where the action they're interested in is happening.

**Comment by linnutee** [comment]
I don't think additional information would make the /community page more useful in a sense. Essentially the page is an extended version of the social media linkage through-out the site – in the footer, in the navigation. 

Follower count itself isn't as much a useful metric, rather comes down to popularity contest. This is also a double-sided sword, as some of the platforms have rather small numbers in comparison to the cc space. I think when it comes to highlighting the follower count, the approach of simply doing the very occasional posts about larger milestones "e.g. cheers for 50k" is what attractively communicates that there's a critical mass behind dcr. 

Most chat platforms are bridged, so finding the activity is likely not a problem. Social media publishers - comes down to personal preference or availability what to follow. These are quite quick to check through. 

Only specific improvement to the social media linkage and community page would be clearing up the hierarchy. The platforms that are most active and/or should be promoted (slack, twitter, github) – need to be on the top of the list. Platforms that are almost dead, potentially be dropped (e.g. forum) to the bottom. There's also inconsistency between footer, navigation linkage and community subpages. Ideally all of those (and any other instances) should follow the same hierarchy in the order icons or cards are presented. Can also consider some grouping between chat platforms and publishers on the community page, so that way each group can have a short description. I think descriptions per platform is overdoing it, as those will end up saying the same things.

**Comment by linnutee** [comment]
Good point. It's currently linking to https://matrix.to/#/+decred:decred.org which opens up the appropriate server. Wondering whether the instruction can be included on that launch page, similar as we got with https://slack.decred.org?

**Comment by noahpierau** [comment]
FYI: this issue was created after a discussion in #writers_room that we should have a dashboard with community statistics. I know it is largely a popularity contest, but some investors / exchanges are asking for it. We were considering including those numbers in the business brief, but the challenge there is that we cannot easily update them. If the community page has those stats, we could simply link there.

As for the matrix/riot question, I remember that @jzbz had a link that automatically changes the home server for a new user. I forgot how he did it, maybe he can explain it himself?

**Comment by jzbz** [comment]
@noahpierau It's possible to pre-populate the form with the home server by specifying it in the link:
https://riot.im/app/#/login?hs_url=https://matrix.decred.org

**Comment by RichardRed0x** [comment]
This is also relevant to #393 - which is about explaining the bridging of comms so that people understand they don't have to look for the platform where most of the community is.
I guess what you mean @linnutee is that this page could be organized around two groups of platforms - bridged chat and then everything else? That seems sensible to me.
Bridged chat would be Matrix, Slack, Discord, RocketChat and irc (although irc probably needs a landing page explaining which channels exist, presently it just dumps you in the general channel). I have seen some discussion of down-playing irc because it has issues (like the person who asked a question may already have left before someone answers), maybe it should be dropped or relegated to the "not-bridged" set.

Matrix could really use a nice custom landing page, that would be very worthwhile.

**Comment by linnutee** [comment]
I meant categorized by type, so slack, telegram, matrix etc as sort of active chat platforms vs facebook, twitter, medium etc as publishers.

**Comment by RichardRed0x** [comment]
How about 3 categories then? 
Bridged char: Matrix, Slack, Discord, Rocket.chat
Un-bridged or less bridged chat: irc, telegram, Kakaotalk, Wechat
Other: Twitter, reddit, youtube, medium, facebook

The reason to separate bridged from un-bridged chat is that people who want to join a chat should know that they're missing out on a lot if they join an un-bridged platform.

**Comment by noahpierau** [comment]
Partially solved by: https://github.com/decred/dcrweb/issues/393

New issue for the Matrix landing page: https://github.com/decred/dcrweb/issues/452

The other improvements are not a priority right now.
