### ISSUE TITLE
Community page - list of GitHub repositories

### ISSUE THREAD

**Issue by RichardRed0x** [decred/dcrweb#378]
I made a [list of GitHub repositories](https://github.com/RichardRed0x/decred-on-github/blob/master/README.md) where Decred-related work happens and where contributions of various types are welcomed. Not sure where to put it, maybe decred.org/community?

**Comment by xaur** [comment]
May be useful for reference: there was a list of user projects on dcrdocs which was removed in [this change](https://github.com/decred/dcrdocs/issues/519). [This](https://github.com/decred/dcrdocs/blob/e4f905eda91c35eb89f39d493ed6802cd778a540/docs/advanced/user-projects.md) is how it looked before the removal.

Yours is a bit different, it lists not projects but GitHub repos. What if there are GitLab repos? ;) How would you define a criteria for inclusion in the list? Is it _some_ repository where the code is open and contribution is possible?

**Comment by linnutee** [comment]
The community subpage isn't relevant for these. We've got a development subpage in the pipeline, which will include reference to the repos.

**Comment by s-ben** [comment]
@RichardRed0x , this is a nice list. I may use/modify this in the Decred Developer Docs I'm working on if that's cool. @linnutee , I wasn't totally sure where the Decred Developer Docs would be linked from (I'm relatively new to the project), but I'm assuming we'll want it on the development subpage (in addition to the Contributing page on dcrdocs). Here's a rough outline of the Developer Docs if you're curious,
https://s_ben.gitlab.io/decred-dev-docs/docs/

As for the question of what repos to list, I think a short list of the important projects is useful. Most contributions happen there. However, there are a bunch more projects people could theoretically contribute to. We also want to mention GitLab if there are projects that live there (@xaur , perhaps you could point me to a couple? I've got the Developer Docs in GitLab for now, but was imagining they would eventually move to GitHub). As for the copy introducing Decred projects, perhaps we could say something like, 

"Decred software is housed in numerous GitHub and GitLab repos. Below is a list of larger projects under continuous development. For a full list of Decred projects, see Decred's GitHub and Gitlab pages."

**Comment by xaur** [comment]
@s_ben no I don't know any projects on GitLab currently, just trying to not design exclusively for GitHub.

Note that some projects (like articles, journal, open source research, video production) could accept contributions from non-developers, therefore links to them should not live only in the dev docs. @RichardRed0x made a good point that Decred would benefit by engaging more non-dev contributors. This would build an understanding that Decred is a place to contribute (and work) not only for developers.

re copy, "housed in" is pretty rare, how about "hosted"?

**Comment by s-ben** [comment]
I agree "hosted" is a better word. 

@xaur , I agree links to non-dev projects should not only live in dev docs. I'm thinking dev docs I might just reuse the 'Software' section of richardred's copy. Also keeping my eye out for opportunities to highlight non-dev contribution opportunities as I continue to wrap my head around the project. Also, good to know about GitLab. I was handed the beginnings of the Developer Docs in a GitLab repo, and have been working there in case the developer I was working with wanted it there. However, it appears it's just me working on it now, and I've come to uncover a fuzzy consensus (here and elsewhere) that the dev docs should eventually live on GitHub. I've seen a few pro-GitLab comments here and there. Presumably because GitHub is now owned by Microsoft. But it looks like any possible transition to GitLab is a bigger, longer-term project. After working with GitLab for the first time on this, I can say that it's a fairly full featured, solid product. However the switching costs (different UI and collaboration tools, admin) would be high. Also, afaik, it's also a VC-backed private company that could get bought by Google in the end anyway.

**Comment by jholdstock** [comment]
devdocs is now live and contains a list of active code repositories: https://devdocs.decred.org/projects/

Unsure what to do with the list of non-dev repos

**Comment by dajohi** [comment]
Use https://github.com/decred/dcrdevdocs
