### ISSUE TITLE
Copywriting request: Onboarding content for staking subpage

### ISSUE THREAD

**Issue by linnutee** [decred/dcrweb#410]
Considering the staking subpage is one potential journey starting point for many users, this page needs some more informative content to provide the insights and benefits to the new users. 

- Initially the content can be housed in another section of the subpage, whilst keeping the rest of the page intact. 
- Needs to consider the onboarding pieces at Decreditons start. 
- Needs to consider the content in the Tour page. 
- Needs to consider the content in Governance page. 
- Provide insight to the basics of Staking – cover the three different types of voting. (references to voting dashboard and politeia). 
- Provide insight to the setup process (very briefly) as well the relation to the VSPs. 
- Add non-intrusive marketing perspective from staking as a way to put ones funds safely. 
- Sync up with proposed language changes. 

Request for involvement #writers-room: Richard-Red, Jazzah

**Comment by Dustorf** [comment]
Decred coin holders can opt-in to project governance by pseudorandomly locking their coins in exchange for tickets in order to earn staking rewards. By participating, stakeholders help secure the network by voting to approve the work of the miners, and gain voting rights on proposed changes to the Decred blockchain and project management via Politeia. For a complete explanation, see the Documentation.

Because tickets are called pseudorandomly and a wallet must be online to vote when a ticket is called, many people use a Voting Service Provider (VSP) using Decrediton or dcrwallet. VSPs lack access to your funds and are tasked with relaying your voting preferences to the network.

The following VSPs have been reviewed by the community.

**Comment by dajohi** [comment]
@alexlyp  says close
