### ISSUE TITLE
Revamp exchange page

### ISSUE THREAD

**Issue by jzbz** [decred/dcrweb#458]
Our exchange page (https://www.decred.org/exchanges/) has become a bit of a mess, while Decred is present on numerous exchanges the reality is that the vast majority of the volume is traded on a handful. It makes little sense to display the exchanges in random order and the filters at the top of the page are mostly wrong.

I propose the following:

Begin the list with the highest liquidity exchanges.
* Binance
* Bittrex
* Huobi
* Poloniex
* OKEx
* Gate

N.B. I'm purposefully excluding exchanges that have blatantly fake volume.

Then list the remainder of the exchanges in alphabetical order.

Create a separate section for "instant exchanges" (alphabetical) with an appropriate header. We will then have:
* Exchanges
* Instant exchanges
* OTC
* Payment processors

This would increase the usefulness of the page immensely in my view.

**Comment by linnutee** [comment]
Added this to the worklist. From a communication and convenience standpoint the categories would be the easiest to go with. However, I disagree with brining in a preference hierarchy here (at least not this straight-forward) and rather prefer to stay true to the present approach of not preferring one or another. 

The root of the problem here is that current random order gives an unfair top position to crappy and questionable exchanges due to the sheer total amount of exchanges. So the legitimate exchanges, should still stay on top, but decred.org shouldn't prefer any of those. 

Keeping in mind this needs to be still functional with even bigger amount of exchanges, I think the key is further improving the filtering system. This was initially designed when there were far less exchanges. The problems above can be also solved by a more elaborate use of the filters. For example: first applying correct tags to all exchanges; adding more specific values that help filter through them better; only displaying high liquidity and instant exchanges tags and having rest hidden by default. This way the page will be more compact in height to begin with and won't bury OTC and PP’s as far down as currently.

**Comment by exitus1** [comment]
The "Nanex" exchange was shut down. It should be removed from the Exchanges list.

**Comment by jzbz** [comment]
@exitus1 good catch. Sent a PR to remove that (#746).

**Comment by exitus1** [comment]
I came across these exchanges which have DCR listed but are not on the Exchanges page.

Instant Exchange: 
https://stealthex.io/

Fiat/Instant Exchange:
https://future1exchangecredit.com/
https://indacoin.com/en-US/buy-bitcoin-with-cardusd

**Comment by jzbz** [comment]
They'd need to be tested by a trusted member of the community before they can be included. "Instant exchanges" pop up and disappear regularly.

**Comment by Dustorf** [comment]
ChangeNOW sent me an email asking to be added. Does that fall into the same category?

**Comment by exitus1** [comment]
> ChangeNOW sent me an email asking to be added. Does that fall into the same category?

I'm not seeing DCR as an available Coin to swap on ChangeNOW. https://imgur.com/a/R6ZWCT2

**Comment by NowPaymentsIO** [comment]
As of today, DCR is available to swap on ChangeNOW. There was a temp tech issue that has been fixed. Thanks!
Another thing: ChangeNOW has a product called NOWPayments, a crypto payment processor, that also supports DCR. Would it be possible to get it added as well?
![Screenshot 2020-02-03 at 16 45 31](https://user-images.githubusercontent.com/54110478/73661137-9d8efd80-46aa-11ea-9c91-88ee14322813.png)

**Comment by jzbz** [comment]
@NowPaymentsIO Yes we can add both ChangeNOW and NOWPayments.

**Comment by NowPaymentsIO** [comment]
@jzbz Great, thank you.
Should we provide you with ChangeNOW and NOWPayments logos?
Do you have any ETA for listing so we can prepare announcements?

**Comment by exitus1** [comment]
https://cryptofacil.com/ has ceased operations since march 15, 2020.

**Comment by exitus1** [comment]
Suggestion: When clicking on an exchange tab, have the link direct the actual DCR pair and not just the exchange's homepage.

Example: I click on the Binance tab and it sends me to https://www.binance.com/en - Ideally, the user should be sent to https://www.binance.com/en/trade/DCR_BTC

**Comment by jzbz** [comment]
> Suggestion: When clicking on an exchange tab, have the link direct to the actual DCR pair and not just the exchange's homepage.
> 
> Example: I click on the Binance tab and it sends me to https://www.binance.com/en - Ideally, the user should be sent to https://www.binance.com/en/trade/DCR_BTC

Issue with that is some exchanges have multiple pairs, in the case of Binance BTC and USDT are available, each would need their own little icon, might be worth opening another issue for.
