### ISSUE TITLE
Show thin banner about consensus votes on top

### ISSUE THREAD

**Issue by xaur** [decred/dcrweb#579]
Since consensus votes are pretty important, here's an idea to (ab)use decred.org as an extra place to remind about them.

Add a minimal banner (24px) on top that signals about pending or ongoing consensus votes.

JS version could pull the data directly from dcrdata, although a decent implementation would also work without JS. In the latter case, the data would be pulled (e.g. hourly) from dcrdata and cached in dcrweb memory.

Idea triggered by [this comment](https://github.com/decred/dcrdata/issues/1009#issuecomment-468222051).

Further possible development of this idea is to also add short numbers about Politeia pending and ongoing votes.

**Comment by linnutee** [comment]
Hrmm not sure if this is too close to end of voting, but we can replace the Pi notice with it. I'll shoot out a an example. 

Mentioning also as we're doing an update to the landing page atm, i'm including a dedicated area for the kind of important signals and announcements.

**Comment by jholdstock** [comment]
Still over two weeks of voting left, I think it is still worth it.

**Comment by xaur** [comment]
Oh if you want to cover current vote I suggest to start with a quick static hack, and then replace it with proper implementation with live data.

**Comment by linnutee** [comment]
Alright threw up a quick design mockup here for implementation. @jholdstock maybe can roll it out? 

Preview: https://xd.adobe.com/view/1600c1d6-8fc3-4ad1-509e-85a8e34b7577-6031/
Specs: https://xd.adobe.com/spec/27e856f2-1dcf-43e6-6b59-5e3f5c29a19b-51d9/

1) Pi replaced w/ LN symbol.
2) Title "Consensus Voting is In-Progress" and could additionally add the agenda ID w/ the bg bubble.
3) In order to fully support the <a href="http://lightning.network">W3C Lightning Network</a>, the current sequence lock consensus rules need to be modified. 
4) Button renamed to "View Voting Tracker", icon removed + spacing adjusted and link to http://voting.decred.org

Please keep in mind to remove altogether when completed. 

[ln-symbol-notification.svg.zip](https://github.com/decred/dcrweb/files/3018326/ln-symbol-notification.svg.zip)

**Comment by xaur** [comment]
Hey thanks for rolling it out so quick!

One thing: current implementation requires to scroll down a bit to see the banner. What I suggested initially is to place a thin ~24px stripe on the very top of the page.
