### ISSUE TITLE
font is too small

### ISSUE THREAD

**Issue by raedah** [decred/dcrweb#613]
https://decred.org/matrix/

-Font on left pane is too small. On a large screen there is a lot of unused space.
-Text on left pane and right pane should be top aligned. Currently they are uneven.

**Comment by otisidev** [comment]
Am on it ..

**Comment by linnutee** [comment]
Any idea who's made this subpage? Seems a copy of the old slack sign-up page (even same visual w/ slack logo) + content wise it's pretty bloated (e.g. long matrix description, repetitions, no hierarchy). Instead of tweaking it, i'd recommend to shoot out a better one that would only contain a far clearer tutorial/flow description for the sign-up. 

Maybe @marcelolustosa or @morphymore?

**Comment by vincent-bekir1** [comment]
> https://decred.org/matrix/
> 
> -Font on left pane is too small. On a large screen there is a lot of unused space.
> -Text on left pane and right pane should be top aligned. Currently they are uneven.

checkout PR/624
