### ISSUE TITLE
Update stats.decred.org with new info from dcrdata.org

### ISSUE THREAD

**Issue by oregonisaac** [decred/dcrweb#631]
stats.decred.org has a great design (imo) and could be a more useful link to share with new and existing community with some added info now available from our own APIs that was not previously available.

https://explorer.dcrdata.org/charts?chart=hashrate&zoom=jfedhcqo-jtvzl0hs is a chart whose information (probably a 12 month snapshot is easiest to look at in a simplified line chart).

The treasure chart could be a nice add as well: https://alpha.dcrdata.org/address/Dcur2mcGjmENx4DhNqDctW5wJCVyT3Qeqkx?chart=balance&zoom=ijhhasg0-jtb0vfk0&bin=month&n=20&start=0&txntype=merged_debit

Once available, the percentage of DCR staked over time would be a great chart/graph for simple line chart, but for now a simple current percentage pulled from DCR data (or just calculated, the info is already on the page) would be useful.

**Comment by jholdstock** [comment]
Hey Isaac.

The correct repo for https://stats.decred.org would be https://github.com/decred/dcr-netstats

This project was initiated because it was an easy way to get a Decred dashboard online with minimal effort. Note that it was forked from `cubedro/eth-netstats`, adapted to work with Decred, and then it has seen no major updates since. 

I believe there is a plan to kill stats.decred.org **very** soon, and redirect requests on that URL to dcrdata.org. @dajohi can probably provide further details on that.
