### ISSUE TITLE
exchanges: category selection buttons

### ISSUE THREAD

**Issue by raedah** [decred/dcrweb#674]
- There is no url parameter set when showing a specific category, so there is no way to link people to directly to a category.

- The category selection buttons are a main feature of this page, but they icons are rather small and non descriptive, with labels only visible if someone happens to use the hover over. Overall, these can be made more prominent on the page to encourage users to use them. 

- It should be obvious to the user which category is currently selected and being displayed.

- OTC trader and Payment Processors are on this page but not immediately noticeable due to them being at the bottom and not being part of the button selections. They should likely be part of the button selection process.

**Comment by johncodesit** [comment]
@raedah is this still an issue? Looking for my first good issue :)

**Comment by jholdstock** [comment]
A lot of time was sunk on this issue in #677, and that ended up going nowhere. I'd say it's not worth investing any further effort into this page because I believe it is earmarked for removal in the medium/long term.

Curating our own list is fraught with problems:

- Exchanges sometimes drop Decred support
- Exchanges change their naming/branding
- Exchanges open and close often
- Exchanges are sometimes hacked
- Exchanges are sometimes flat out scams
- The categorizations of "High liquidity", "decentalized" and "atomic swaps" are subject to debate

Given the issues, and that its extremely easy to find exchanges using a search engine, there isn't much value in maintaining the page.
