### ISSUE TITLE
Refactor and rename downloads

### ISSUE THREAD

**Issue by jzbz** [decred/dcrweb#682]
* Rename downloads to wallets (https://decred.org/wallets/).
* Remove all mining software links, nobody GPU mines Decred anymore.
* Add hardware wallet section above third party wallet section, there will need to be some way to indicate which HW wallets are supported by Decrediton which have their own native wallets and which do both.

**Comment by s-ben** [comment]
+1 depricating mining stuff. It's essentially impossible to get any blocks GPU mining (tried on my macbook pro when i was first looking into decred and didn't even come close). We updated the docs (which you can still download the mining software from) a while back to give this warning:

"Decred uses the BLAKE-256 hashing function. PoW mining can be done using GPUs. However, ASICs that mine DCR are now available, and since their introduction the PoW difficulty has become high enough to make GPU mining unlikely to be profitable."

someone really interested in mining presumably would find the downloads in the docs,
https://docs.decred.org/mining/overview/

**Comment by jholdstock** [comment]
Great idea

**Comment by s-ben** [comment]
As for the hardware wallets, the recently added [hardware wallets](https://docs.decred.org/wallets/hardware-wallets/) page on dcrdocs is pretty much just a simple description of what a hardware wallet is and a list of supported wallets. Could possibly reuse text and link to docs?

P.S. the trezor blockbook integration appears to be nearing completion ([trezor PR](https://github.com/trezor/blockbook/pull/216)).

**Comment by jzbz** [comment]
@s-ben Linking to the docs might be the best way of dealing with the question of what HW is supported where

**Comment by s-ben** [comment]
Was wanting to add more info on HW wallet support to the docs regardless. Have created dcrdocs [Issue](https://github.com/decred/dcrdocs/issues/962).

**Comment by linnutee** [comment]
Might still leave some reference to the mining software in docs then. But otherwise a sound simplification to change from Downloads to Wallets.

**Comment by noahpierau** [comment]
Can we also include download links to both of the mobile wallets on the new page? 

It also needs to make clear which wallets support PoS (currently only Decrediton and CLI), we get this question too many times!
