### ISSUE TITLE
Past Contributors page

### ISSUE THREAD

**Issue by xaur** [decred/dcrweb#744]
iirc our /contributors page only lists "recently active contributors" and has periodic cleanups. This keeps the page relevant but it removes credit for work done in the past.

I suggest to add explicit "Past Contributors" page and move people there after a certain period of inactivity. Also, all people who were removed in previous cleanups can be restored in that place.

**Comment by Dustorf** [comment]
I actually think the Contributors page is unnecessary. It's a hassle to maintain, and it only serves to communicate that there are plenty of people working on Decred, which I think is obvious without it. So, I'd prefer to remove it, or replace it with some summary stats that wouldn't need maintenance.

**Comment by xaur** [comment]
I wouldn't remove the Contributors page at this point. It serves as a Hall of Fame and is an incentive in some cases, e.g. [quoting](https://medium.com/@richardred/working-for-the-decred-dae-a9cfb17686fa) @RichardRed0x

> This is how I look when I’m contributing to Decred. Getting one of these cool portraits was in my top 5 reasons for wanting to become a contractor.

**Comment by RichardRed0x** [comment]
I agree, the contributors page is useful for finding out who is working on the project. I don't think it should be removed unless it is replaced with something else. A past contributors page would be a nice addition imo.

**Comment by linnutee** [comment]
Not much preference on it, but objectively I do see a few more cons to this than pro's. Background context: the contributors page was added initially to dcrweb during an earlier update when there was little content and the project seemed obscure. Highlighting team members was essentially a marketing effort to help legitimize the project, showing there’s real people/companies working behind it etc. As including real photos was both a privacy and consistency concern, we got to the solution of working out these simple portraits. As mentioned above, this did lead to a positive “work experience” effect, since the hand drawn portraits of persons are of much more value than some generated graphics. 

Cons: 
- Hassle to maintain
- Likely not accurate for the most time
- Data being pulled to various shady sites, intrusive listings  

Pros: 
- Positive incentive by acknowledgement /crediting
- Getting custom DCR portraits

So maybe we can figure out some compromised way for replacing it with a disciplines summary and some references to contributing/becoming a contractor.

The hall of fame idea imo makes for a better fit as microproject that is individually managed by someone, and has an optional opt-in/out for those with privacy concerns. A list made with good intent in mind, unfortunately risks being abused by others. 

Regarding the portraits, I've got an issue in my tasklist to create request/issue templates for /dcrdesign repo. Will include one specifically for the portraits.

**Comment by Dustorf** [comment]
If someone did pick up the HoF idea and ran with it, they would need to create rules, such as whether someone would have to be retired from the project, and how long after retirement they would have to wait to be nominated. What's the nomination process? Is there voting functionality in Politeia for this? Has bee made an issue on it?

**Comment by xaur** [comment]
Damnit @Dustorf! [Yes I did](https://github.com/decredcommunity/issues/issues/52). About a year ago. I'm not feeling shame.

Agreed it will need a clear governance process. The rule I would start with "if you made something useful for Decred, you agree for it to be listed in HoF _and_ agree that it will stay there forever, we'll review and add it". From that I'll iterate and document the rules. It will take time to get right.

@linnutee great points. Positive "work experience", acknowledgint contributions, and the portraits are things I care about most. If we can retain that I don't even mind removing the page alltogether, if this idea becomes popular.

**Comment by jamiekeefer** [comment]
Put a link to: https://github.com/orgs/decred/people or use the API to dynamically update the contributors page: https://developer.github.com/v3/repos/#list-contributors.

**Comment by xaur** [comment]
I think the set of contributors is not equal to the set of decred gh org members.

**Comment by alexlyp** [comment]
Has been discussed among web ops and determined that it wouldn't fit with the current new website design.  Closing.

**Comment by xaur** [comment]
Eer.. How can design dictate which content we want to present? Shouldn't it _serve_ in presenting the chosen content?
