### ISSUE TITLE
Menu Widget Has Misleading Mouse Pointer

### ISSUE THREAD

**Issue by eharris128** [decred/dcrweb#748]
- Anywhere in the whitespace inside of the menu that has the class navigation the cursor will display as a pointer upon hover. Ideally, we would only have a cursor as a pointer when hovering over something clickable.
![image](https://user-images.githubusercontent.com/24369866/69106705-36639480-0a3d-11ea-9876-4f08126bc50c.png)

**Comment by jholdstock** [comment]
Hi @eharris128,

I have merged your PR, however it did not automatically close this issue because you inserted the word "issue" into `closes issue #748`.

Documentation on how to automatically close issues can be found [here](https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords).

Closing this issue manually now - thanks again for your contribution!
